services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: is_it
      POSTGRES_PASSWORD: verysecurepassword
      POSTGRES_DB: is_it_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
