"""reduce author and text limits for epigrams

Revision ID: 0a291bfb2345
Revises: 3a869160d685
Create Date: 2025-10-11 11:30:47.355895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a291bfb2345'
down_revision: Union[str, Sequence[str], None] = '3a869160d685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigrams', 'text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('epigrams', 'author',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_epigrams_client_created_desc'), table_name='epigrams', postgresql_include=['id', 'text', 'author'])
    op.drop_index(op.f('uq_epigrams_text_author_ci'), table_name='epigrams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_epigrams_text_author_ci'), 'epigrams', [sa.literal_column('lower(text::text)'), sa.literal_column("COALESCE(lower(author::text), ''::text)")], unique=True)
    op.create_index(op.f('idx_epigrams_client_created_desc'), 'epigrams', ['client_id', sa.literal_column('created_at DESC')], unique=False, postgresql_include=['id', 'text', 'author'])
    op.alter_column('epigrams', 'author',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('epigrams', 'text',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
