"""Create initial epigram table

Revision ID: dd4c7c1207f7
Revises: 
Create Date: 2025-10-10 08:10:51.265669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4c7c1207f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epigrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='0 pending 1 approved 2 rejected'),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.CheckConstraint('status in (0, 1, 2)', name='ck_epigrams_status_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epigrams_author'), 'epigrams', ['author'], unique=False)
    op.create_index(op.f('ix_epigrams_client_id'), 'epigrams', ['client_id'], unique=False)
    op.create_index(op.f('ix_epigrams_text'), 'epigrams', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epigrams_text'), table_name='epigrams')
    op.drop_index(op.f('ix_epigrams_client_id'), table_name='epigrams')
    op.drop_index(op.f('ix_epigrams_author'), table_name='epigrams')
    op.drop_table('epigrams')
    # ### end Alembic commands ###
